/*

Points to note:
(1) run_check.sh: source yosys environment, then run_check.sh to automatically check if output .blif is logically equivalent to that generated by yosys
(2) Limitations: current code only parses one modules
(3) Assumed verilog syntax is correct
(4) Not all verilog cases are handled
(5) Primary purpose to have parsing correct, not yet optimized. Example, cascading logics are split into two-input gates only

Next steps: 
(1) Add Bit-Blasting for Vector Buses: Support multi-bit registers and wires (e.g., input [3:0] A; and assign Y = A + 1;).
(2) Multiple modules
(3) Implement logic optimization
(4) Implement ABC Technology Mapping: Feed your working .blif file into ABC to automatically map your gates to LUT 4).

Here is the comprehensive architectural walk-through of the parsing logic inside basic_compiler_1.cpp formatted for your engineering documentation.
------------------------------
## EDA Tool Architecture: Synthesizer Parsing Logic
The BlifSynthesizer engine transforms a subset of synthesizable Register-Transfer Level (RTL) SystemVerilog/Verilog source code into a flattened Berkeley Logic Interchange Format (BLIF) gate-level netlist.
The compiler operates in a Single-Pass Line-by-Line Tokenization model, executing three primary phases: Lexical Sanitization, Syntactic Block Discrimination, and RTL-to-Gate Translation.
------------------------------
## Architectural Data Model
Before parsing begins, internal data structures (struct Netlist) track all hardware entities as single-bit scalar nodes:

* inputs / outputs: Track boundary primary I/O pins.
* wires: Automatically tracks internal intermediate signals or variables.
* gates: Stores instances of combinational operators (AND, OR, XOR, etc.) paired with an input_nets array and an output_net string.
* latches: Stores sequential state elements (D Flip-Flops) mapping inputs (input_d) to synchronized storage outputs (output_q).

------------------------------
## Phase 1: Lexical Sanitization (clean())
Hardware description languages contain variable whitespace and stylistic structural separators. The utility method clean() strips out noise line-by-line using C++ std::remove to prevent token pollution:

   1. Removes spaces ( ) and semicolons (;).
   2. Removes block brackets or parentheses ((, )).
   3. Removes structural commas (,) commonly found in ANSI port list headers.

Example: "input A, B ;" is prepared into blocks like "input", "A", "B".
------------------------------
## Phase 2: Global Line Discrimination (main())
The main loop inside int main() reads the source file line-by-line via std::getline(), identifies leading keyword prefixes using rfind(), and routes them to dedicated compilers:

   1. Structural Pruning: If a line starts with module or endmodule, the parser skips it entirely (continue). This strips the high-level behavioral wrapper so only raw declarations and logic components are synthesized.
   2. Declarations: Routed to parseDeclaration() if prefixed with input, output, or wire.
   3. Dataflow Assignments: Routed to parseAssignment() if prefixed with assign.
   4. Clocked Sequential Behaviors: Routed to parseAlways() if prefixed with always or always_ff.

------------------------------
## Phase 3: Detailed Compiler Engines## Step A: Hardware Interface Mapping (parseDeclaration)

Verilog Source: "input A, B;"  -->  Netlist State: inputs = ["A", "B"]


* Mechanism: Instantiates a string stream (std::stringstream) to read words sequentially.
* Logic: The first word determines the hardware tier type (input, output, or wire). Every following word on that line is cleaned of syntax marks and added to its respective target vector in the global netlist.

## Step B: Combinational Expansion (parseAssignment)

Verilog Source: "assign Y = A & B & C;"

## Step C: Sequential Latch Inference (parseAlways)

Verilog Source: "always @(posedge clk) begin Q <= D; end"

------------------------------
## Phase 4: BLIF Translation (exportToBlif)
Once the file stream hits EOF (End-of-File), the string utilities compute output paths (replacing .v with .blif), and exportToBlif processes the aggregated structural data into low-level Sum-of-Products (SOP) tables:

   1. .model / .inputs / .outputs: Emits standard text definitions mapping primary port lines.
   2. .latch Translation: Writes explicit memory blocks for all identified registers:
   
   .latch <input_d> <output_q> <re/fe> <clock> 2
   
   3. .names Truth Table Generation: Converts each gate structure into binary match strings:
   * AND/NOR/NOT/BUF: Emits standard deterministic rows (e.g., an N-input AND prints a row of N ones: 1111 1).
      * NAND/OR: Emits iterative arrays containing don't-care markers (-) to represent individual logic satisfying states.
      * XOR/XNOR: Executes a $2^N$ loop permutation block. It tests the Hamming weight (number of active 1 bits) for every possible binary input combination and automatically generates precise odd or even parity rows mapped to output truth targets.
   
------------------------------
Here are both the Flowchart Diagram and the Architecture Block Diagram to include in your documentation. These visual aids map directly out of the clean string parsing and loop interception execution sequences built into your unified C++ source file.
------------------------------
## 1. Compiler Architecture Block Diagram
This block diagram maps out the static hardware component separation and how strings decouple into specific scalar structures inside the Netlist object memory workspace.

+---------------------------------------------------------------------------------+

|                                 SOURCE FILE (.v)                                |
+---------------------------------------------------------------------------------+
                                         |
                                         v
+---------------------------------------------------------------------------------+

|                         LINE READER LOOP (std::getline)                         |
+---------------------------------------------------------------------------------+
                                         |
                        +----------------+----------------+

                        | Strips Spaces, Brackets, Commas |
                        v
+---------------------------------------------------------------------------------+

|                            LEXICAL SANITIZATION (clean)                         |
+---------------------------------------------------------------------------------+
                                         |
         +-------------------------------+-------------------------------+

         | (Prefix Check)                | (Prefix Check)                | (Prefix Check)
         v                               v                               v
+------------------+           +------------------+           +------------------+

| parseDeclaration |           |  parseAssignment |           |   parseAlways    |
+------------------+           +------------------+           +------------------+

         |                               |                               |
         | Identifies Ports              | Tokenizes Logic               | Loops Sub-Lines
         | & Wire Nets                   | & Drops Operators             | Until "end"
         v                               v                               v
+---------------------------------------------------------------------------------+

|                            NETLIST WORKSPACE MEMORY                             |
|                                                                                 |
|   .inputs [X, Y]     .outputs [Z]     .wires [w1]     .gates []     .latches [] |
+---------------------------------------------------------------------------------+
                                         |
                                         v
+---------------------------------------------------------------------------------+

|                           EXPORT PIPELINE (exportToBlif)                        |
+---------------------------------------------------------------------------------+
                                         |
                        +----------------+----------------+

                        | Computes SOP Truth Tables       |
                        v
+---------------------------------------------------------------------------------+

|                                OUTPUT FILE (.blif)                              |
+---------------------------------------------------------------------------------+

------------------------------
## 2. Flowchart Diagram (Execution Logic)
This structural flowchart details the operational state machine inside main(). It visually highlights the unique mechanism where parseAlways() temporarily hijacks the primary file reader stream (infile) to parse independent sequential block bodies before handing looping control back to the global file scanner scope.

                  [ START COMPILER ]
                          |
                          v
               Open Input File Stream
                          |
+------------------->  [ EOF? ] ----( Yes )----+

|                         |                    |
|                      ( No )                  v

|                         |          Compute Output Paths
|               Read Line via getline()   (Change extension to .blif)

|                         |                    |
|               Strip Outer Spaces             v

|                         |          Invoke exportToBlif()
|       +-------< Is Line Empty? >             |
|       |                 |                    |
|     (Yes)             ( No )                 |
|       |                 |                    v
|       |    Is Line "module"/"endmodule"?   [ GENERATION COMPLETE ]
|       |                 |
|       +---------(Yes)   |
|       |                 |
|       |               ( No )
|       |                 |
|       |       +---------+---------+-------------------+
|       |       |                   |                   |
|       |  Prefix "input"   Prefix "assign"      Prefix "always"
|       |  "output"/"wire"          |            "always_ff"
|       |       |                   |                   |
|       |       v                   v                   v
|       | parseDeclaration()  parseAssignment()   parseAlways()
|       |       |                   |                   |
|       |       |                   |           [ HIJACK infile STREAM ]
|       |       |                   |           Read sub-lines in loop
|       |       |                   |           Until "end"/"endmodule"
|       |       |                   |           Instantiate .latches
|       |       |                   |                   |
|       |       |                   |           [ RELEASE STREAM ]
|       +-------+-------------------+-------------------+

------------------------------
## Summary Checklist for Documentation
When inserting this block layout into design logs, verify these processing invariants:

* The Parser Invariant: Indentation variation does not impact block choices because find_first_not_of(" \t\r\n") transforms raw indented expressions into deterministic left-aligned prefixes.
* The Stream Invariant: Passing std::ifstream& infile by reference into parseAlways() guarantees the program pointer steps linearly through memory rather than resetting or duplicating line inspections.

*/


#include <iostream>
#include <fstream>
#include <string>
#include <vector>
#include <sstream>
#include <algorithm>

// Represents combinational logic gates mapped to BLIF truth tables
struct Gate {
    std::string op;             // AND, OR, XOR, NAND, NOR, XNOR, NOT, BUF
    std::string output_net;
    std::vector<std::string> input_nets;
};

// Represents sequential state elements mapped to BLIF .latch
struct Latch {
    std::string input_d;
    std::string output_q;
    std::string clock;
    std::string edge_type;      // "re" (rising/posedge) or "fe" (falling/negedge)
    int init_val;               // 0, 1, or 2 (don't care / uninitialized)
};

struct Netlist {
    std::vector<std::string> inputs;
    std::vector<std::string> outputs;
    std::vector<std::string> wires;
    std::vector<Gate> gates;
    std::vector<Latch> latches;
};

class BlifSynthesizer {
private:
    Netlist netlist;

    std::string clean(std::string str) {
        //C++14; c++20/23: str.erase(str, ' ')
        str.erase(std::remove(str.begin(), str.end(), ' '), str.end());
        str.erase(std::remove(str.begin(), str.end(), ';'), str.end());
        str.erase(std::remove(str.begin(), str.end(), '('), str.end());
        str.erase(std::remove(str.begin(), str.end(), ')'), str.end());
        str.erase(std::remove(str.begin(), str.end(), ','), str.end());
        //std::cout << str << std::endl;
        return str;
    }

    void registerWire(const std::string& net) {
        if (std::find(netlist.outputs.begin(), netlist.outputs.end(), net) == netlist.outputs.end() &&
            std::find(netlist.inputs.begin(), netlist.inputs.end(), net) == netlist.inputs.end() &&
            std::find(netlist.wires.begin(), netlist.wires.end(), net) == netlist.wires.end()) {
            netlist.wires.push_back(net);
        }
    }

public:
    void parseDeclaration(const std::string& line) {
        // std::stringstream ss(line); wraps the input line in a stream buffer, allowing you to extract words one by one using standard extraction operators (>>), which automatically split on whitespace.
        std::stringstream ss(line);
        std::string type, token;
        ss >> type; // Reads the very first word of the line into type. For example, if the line is "wire a, b, c;", type becomes "wire".
        while (ss >> token) {
            token = clean(token);
            if (token.empty()) continue;

        // CRITICAL FILTER: Skip the "reg" modifier so it doesn't leak into BLIF as a port name!
            if (token == "reg") continue;
            if (token.empty()) continue;
            if (type == "input")  netlist.inputs.push_back(token);
            if (type == "output") netlist.outputs.push_back(token);
            if (type == "wire")   netlist.wires.push_back(token);
        }
    }

    void parseAssignment(const std::string& line) {
        // 1. Identify structural boundaries
        size_t assign_pos = line.find("assign");
        size_t eq_pos = line.find("=");
        size_t semi_pos = line.find(";");

        if (assign_pos == std::string::npos || eq_pos == std::string::npos) return;

        // 2. Extract and clean the Left-Hand Side (LHS)
        std::string lhs = line.substr(assign_pos + 6, eq_pos - (assign_pos + 6));
        lhs = clean(lhs);
        if (lhs.empty()) return;

        // 3. Extract and trim the full Right-Hand Side (RHS) expression
        size_t rhs_start = eq_pos + 1;
        size_t rhs_len = (semi_pos != std::string::npos) ? (semi_pos - rhs_start) : std::string::npos;
        std::string rhs = line.substr(rhs_start, rhs_len);

        size_t first_char = rhs.find_first_not_of(" \t\r\n");
        size_t last_char = rhs.find_last_not_of(" \t\r\n");
        if (first_char == std::string::npos) return;
        rhs = rhs.substr(first_char, last_char - first_char + 1);

        // 4. Check for standard outer inverted wrapper: ~( ... )
        bool is_inverted = false;
        if (rhs.length() > 3 && rhs[0] == '~' && rhs[1] == '(' && rhs.back() == ')') {
            is_inverted = true;
            rhs = rhs.substr(2, rhs.length() - 3); // Strip "~(" and ")"
        }

        // 4.5 Normalize Unary Tildes: Strip white spaces immediately following a '~'
        // This turns layouts like "assign Y = A & ~ B;" into "assign Y = A & ~B;"
        std::string normalized_rhs = "";
        for (size_t i = 0; i < rhs.length(); ++i) {
            normalized_rhs += rhs[i];
            if (rhs[i] == '~') {
                // Skip any spaces or tabs following the tilde
                while (i + 1 < rhs.length() && (rhs[i + 1] == ' ' || rhs[i + 1] == '\t')) {
                    i++;
                }
            }
        }

        // 5. Pre-tokenize the RHS: pad binary operators with spaces. 
        // We leave tildes '~' untouched so they stay glued to their nets (e.g. "~B")
        std::string safe_rhs = "";
        for (char ch : normalized_rhs) {
            if (ch == '&' || ch == '|' || ch == '^') {
                safe_rhs += " ";
                safe_rhs += ch;
                safe_rhs += " ";
            } else {
                safe_rhs += ch;
            }
        }

        // 6. Read tokens out of safe_rhs using stringstream
        std::stringstream ss(safe_rhs);
        std::vector<std::string> tokens;
        std::string tok;
        while (ss >> tok) {
            tok = clean(tok);
            if (!tok.empty()) tokens.push_back(tok);
        }

        if (tokens.empty()) return;

        // =========================================================================
        // CASE A: Single-operand (Direct BUF pass-through or attached unary NOT)
        // Examples: assign Y = C; | assign Y = ~C;
        // =========================================================================
        if (tokens.size() == 1) {
            Gate gate;
            gate.output_net = lhs;

            if (is_inverted) {
                gate.op = "NOT";
                gate.input_nets.push_back(tokens[0]);
            } else if (tokens[0][0] == '~') {
                gate.op = "NOT";
                gate.input_nets.push_back(tokens[0].substr(1)); // Strip leading tilde
            } else {
                gate.op = "BUF";
                gate.input_nets.push_back(tokens[0]);
            }

            registerWire(lhs);
            netlist.gates.push_back(gate);
            return;
        }

        // =========================================================================
        // CASE B: Two tokens (Usually a syntax abnormality that should now be resolved by 4.5)
        // =========================================================================
        if (tokens.size() == 2) {
            Gate gate;
            gate.output_net = lhs;

            if (tokens[0] == "~") {
                gate.op = is_inverted ? "BUF" : "NOT"; 
                gate.input_nets.push_back(tokens[1]);
                
                registerWire(lhs);
                netlist.gates.push_back(gate);
            } else {
                return; // Unhandled syntax error
            }
            return;
        }

        // =========================================================================
        // CASE C: Multi-operand expression (Supports mixed operators, precedence, & inline NOTs)
        // Examples: A & ~B | C | A & ~ B | C
        // =========================================================================
        if (tokens.size() >= 3) {
            auto getPrecedence = [](const std::string& op) {
                if (op == "&") return 2;
                if (op == "|" || op == "^") return 1;
                return 0;
            };

            std::vector<std::string> net_stack;
            std::vector<std::string> op_stack;
            static int tmp_wire_id = 0;

            auto collapseValue = [&](bool is_final = false) {
                if (op_stack.empty() || net_stack.size() < 2) return;

                std::string op = op_stack.back(); op_stack.pop_back();
                std::string right = net_stack.back(); net_stack.pop_back();
                std::string left = net_stack.back(); net_stack.pop_back();

                std::string out_wire;
                if (is_final) {
                    out_wire = lhs;
                    registerWire(lhs);
                } else {
                    out_wire = "_tmp_" + std::to_string(tmp_wire_id++);
                    registerWire(out_wire);
                }

                Gate sub_gate;
                sub_gate.output_net = out_wire;
                sub_gate.input_nets = {left, right};

                if (op == "&")      sub_gate.op = (is_final && is_inverted) ? "NAND" : "AND";
                else if (op == "|") sub_gate.op = (is_final && is_inverted) ? "NOR"  : "OR";
                else if (op == "^") sub_gate.op = (is_final && is_inverted) ? "XNOR" : "XOR";

                netlist.gates.push_back(sub_gate);
                net_stack.push_back(out_wire);
            };

            // Shunting-yard processing loop
            for (size_t i = 0; i < tokens.size(); ++i) {
                if (i % 2 == 0) {
                    std::string target_net = tokens[i];
                    
                    // INLINE NEGATION CHECK: Triggers because step 4.5 guaranteed "~B" is unified
                    if (target_net[0] == '~') {
                        std::string actual_wire = target_net.substr(1); // Extract "B"
                        std::string not_wire = "_tmp_" + std::to_string(tmp_wire_id++);
                        registerWire(not_wire);
                        
                        Gate not_gate;
                        not_gate.output_net = not_wire;
                        not_gate.input_nets = {actual_wire};
                        not_gate.op = "NOT";
                        
                        netlist.gates.push_back(not_gate);
                        net_stack.push_back(not_wire); // Push the inverted temp wire instead
                    } else {
                        net_stack.push_back(target_net);
                    }
                } else {
                    std::string current_op = tokens[i];
                    while (!op_stack.empty() && getPrecedence(op_stack.back()) >= getPrecedence(current_op)) {
                        collapseValue(false);
                    }
                    op_stack.push_back(current_op);
                }
            }

            // Flush remaining operations
            while (op_stack.size() > 1) {
                collapseValue(false);
            }

            // Emit the final root gate directly into lhs
            if (op_stack.size() == 1) {
                collapseValue(true);
            }
        }
    }

    void parseAlways(const std::string& first_line, std::ifstream& infile) {
        bool is_posedge = (first_line.find("posedge") != std::string::npos);
        bool is_negedge = (first_line.find("negedge") != std::string::npos);
        if (!is_posedge && !is_negedge) return;

        // 1. Extract Clock Handle
        std::string clock_name = "clk";
        size_t pos = is_posedge ? first_line.find("posedge") : first_line.find("negedge");
        if (pos != std::string::npos) {
            size_t start = first_line.find_first_not_of(" \t", pos + 7);
            size_t end = first_line.find_first_of(" \t)", start);
            if (start != std::string::npos && end != std::string::npos) {
                clock_name = first_line.substr(start, end - start);
                clock_name.erase(std::remove(clock_name.begin(), clock_name.end(), ')'), clock_name.end());
                clock_name.erase(std::remove(clock_name.begin(), clock_name.end(), ' '), clock_name.end());
            }
        }

        // 2. Consume multi-line body
        std::vector<std::string> body_lines;
        std::string raw_line;
        int block_depth = (first_line.find("begin") != std::string::npos) ? 1 : 0;
        bool seen_first_begin = (block_depth > 0);

        while (std::getline(infile, raw_line)) {
            size_t first = raw_line.find_first_not_of(" \t\r\n");
            if (first == std::string::npos) continue;
            std::string line = raw_line.substr(first);

            if (line.find("begin") != std::string::npos) {
                block_depth++;
                seen_first_begin = true;
            }
            body_lines.push_back(line);
            if (line.find("end") != std::string::npos) {
                block_depth--;
                if (seen_first_begin && block_depth <= 0) break;
            }
        }

        std::string target_q = "";
        std::string rst_signal = "";
        int reset_val = 0;
        std::string d_input = "";
        bool in_reset_branch = false;

        // 3. Inspect body lines for reset condition and data inputs
        for (const std::string& line : body_lines) {
            if (line.find("if") != std::string::npos) {
                in_reset_branch = true;
                // Extract the reset signal name inside if (...)
                size_t p_start = line.find('(');
                size_t p_end = line.find(')');
                if (p_start != std::string::npos && p_end != std::string::npos && p_end > p_start) {
                    rst_signal = clean(line.substr(p_start + 1, p_end - p_start - 1));
                }
            }
            if (line.find("else") != std::string::npos) {
                in_reset_branch = false;
            }

            size_t arrow_pos = line.find("<=");
            if (arrow_pos == std::string::npos) continue;

            std::string lhs = clean(line.substr(0, arrow_pos));
            std::string rhs = clean(line.substr(arrow_pos + 2));

            if (lhs.find("if") == 0) {
                size_t cl_paren = lhs.find(')');
                if (cl_paren != std::string::npos) lhs = clean(lhs.substr(cl_paren + 1));
            }
            if (lhs.rfind("else", 0) == 0) {
                lhs = clean(lhs.substr(4));
            }

            if (in_reset_branch) {
                target_q = lhs;
                if (rhs.find('0') != std::string::npos) reset_val = 0;
                else if (rhs.find('1') != std::string::npos) reset_val = 1;
            } else {
                target_q = lhs;
                d_input = rhs;
            }
        }

        // 4. Build the Synchronous Reset MUX and Latch
        if (!target_q.empty() && !d_input.empty()) {
            std::string latch_d_net = d_input;

            // If an active-high synchronous reset exists, synthesize: latch_d = (~rst & d_input)
            if (!rst_signal.empty() && reset_val == 0) {
                latch_d_net = "_sync_rst_" + target_q;
                registerWire(latch_d_net);

                Gate rst_mux_gate;
                rst_mux_gate.output_net = latch_d_net;
                rst_mux_gate.input_nets = {rst_signal, d_input};
                // Custom op or modeled as an AND with negated first input:
                // .names rst d_input latch_d_net -> row: "01 1"
                rst_mux_gate.op = "AND_NOT_FIRST"; 
                netlist.gates.push_back(rst_mux_gate);
            }

            Latch latch;
            latch.input_d = latch_d_net;
            latch.output_q = target_q;
            latch.edge_type = is_negedge ? "fe" : "re";
            latch.clock = clock_name;
            latch.init_val = reset_val;

            registerWire(target_q);
            registerWire(latch_d_net);
            netlist.latches.push_back(latch);
        }
    }




    void exportToBlif(const std::string& model_name, const std::string& output_filename) {
        std::ofstream outfile(output_filename);
        if (!outfile.is_open()) {
            std::cerr << "Error: Could not open output file: " << output_filename << std::endl;
            return;
        }

        outfile << "# Generated by Extended C++ BLIF Synthesizer\n";
        outfile << ".model " << model_name << "\n";

        // Primary Inputs
        outfile << ".inputs";
        for (const auto& in : netlist.inputs) outfile << " " << in;
        outfile << "\n";

        // Primary Outputs
        outfile << ".outputs";
        for (const auto& out : netlist.outputs) outfile << " " << out;
        outfile << "\n\n";

        // 1. Synthesize Clocked Sequential Latches
        for (const auto& l : netlist.latches) {
            outfile << ".latch " << l.input_d << " " << l.output_q << " "
                    << l.edge_type << " " << l.clock << " " << l.init_val << "\n";
        }
        if (!netlist.latches.empty()) outfile << "\n";

        // 2. Synthesize Combinational Logic Networks
        for (const auto& gate : netlist.gates) {
            size_t n = gate.input_nets.size();
            outfile << ".names";
            for (const auto& in : gate.input_nets) outfile << " " << in;
            outfile << " " << gate.output_net << "\n";

            if (gate.op == "BUF") {
                outfile << "1 1\n";
            } else if (gate.op == "NOT") {
                outfile << "0 1\n";
            } else if (gate.op == "AND") {
                outfile << std::string(n, '1') << " 1\n";
            } else if (gate.op == "NAND") {
                for (size_t i = 0; i < n; ++i) {
                    std::string row(n, '-');
                    row[i] = '0';
                    outfile << row << " 1\n";
                }
            } else if (gate.op == "OR") {
                for (size_t i = 0; i < n; ++i) {
                    std::string row(n, '-');
                    row[i] = '1';
                    outfile << row << " 1\n";
                }
            } else if (gate.op == "NOR") {
                outfile << std::string(n, '0') << " 1\n";
            } else if (gate.op == "XOR" || gate.op == "XNOR") {
                // currently handles cascading XOR/XNOR but this should never happen because in the parseAssignment, there is going to be temporary internal wires to deal with cascading situations.
                size_t total_combinations = (size_t)1 << n;
                for (size_t i = 0; i < total_combinations; ++i) {
                    int ones_count = 0;
                    std::string row = "";
                    for (size_t bit = n; bit > 0; --bit) {
                        if ((i >> (bit - 1)) & 1) {
                            row += "1";
                            ones_count++;
                        } else {
                            row += "0";
                        }
                    }
                    bool parity = (ones_count % 2 != 0);
                    if (gate.op == "XNOR") parity = !parity;
                    if (parity) {
                        outfile << row << " 1\n";
                    }
                }
            } else if (gate.op == "AND_NOT_FIRST") {
            // Generates: when input[0] == 0 and input[1] == 1, output = 1
            outfile << "01 1\n";
            }

            outfile << "\n";
        }

        outfile << ".end\n";
        outfile.close();
        std::cout << "Successfully synthesized BLIF to: " << output_filename << std::endl;
    }
};

int main(int argc, char* argv[]) {
    if (argc < 2) {
        std::cerr << "Usage: " << argv[0] << " <source.v>" << std::endl;
        return 1;
    }

    std::string input_filepath = argv[1];
    std::ifstream infile(input_filepath);
    if (!infile.is_open()) {
        std::cerr << "Error: Cannot open file " << input_filepath << std::endl;
        return 1;
    }

    BlifSynthesizer synth;
    std::string line;

    while (std::getline(infile, line)) {
        size_t first = line.find_first_not_of(" \t\r\n");
        if (first == std::string::npos) continue;
        std::string trimmed = line.substr(first);

        // Ignore empty lines, module wrappers, or end signals in global scope
        // Why use this instead of find? It is an optimization. Regular .find("module") scans the entire length of the string looking for a match. By using .rfind("module", 0), the CPU only looks at the very first few characters and stops instantly if they don't match, saving processing time.
        if (trimmed.rfind("module", 0) == 0 || trimmed.rfind("endmodule", 0) == 0) {
            continue;
        }

        if (trimmed.rfind("input", 0) == 0 || trimmed.rfind("output", 0) == 0 || trimmed.rfind("wire", 0) == 0) {
            synth.parseDeclaration(trimmed);
        } else if (trimmed.rfind("assign", 0) == 0) {
            synth.parseAssignment(trimmed);
        } else if (trimmed.rfind("always", 0) == 0 || trimmed.rfind("always_ff", 0) == 0) {
            synth.parseAlways(trimmed, infile);
        }
    }
    infile.close();

    size_t last_dot = input_filepath.find_last_of(".");
    std::string base_name = (last_dot == std::string::npos) ? input_filepath : input_filepath.substr(0, last_dot);
    std::string output_filepath = base_name + ".blif";
    size_t last_slash = base_name.find_last_of("\\");
    std::string model_name = (last_slash == std::string::npos) ? base_name : base_name.substr(last_slash + 1);
    
    synth.exportToBlif(model_name, output_filepath);
    
    return 0;
}