#include <iostream>
#include <string>
#include <vector>
#include <sstream>
#include <algorithm>

// Primitive gates mapped directly to Yosys internal structural cells
struct YosysGate {
    std::string type;            // AND, OR, NOT
    std::string output_net;
    std::vector<std::string> input_nets;
};

struct Netlist {
    std::vector<std::string> inputs;
    std::vector<std::string> outputs;
    std::vector<std::string> wires;
    std::vector<YosysGate> gates;
};

class YosysCompatibleSynthesizer {
private:
    Netlist netlist;

    std::string clean(std::string str) {
        str.erase(std::remove(str.begin(), str.end(), ' '), str.end());
        str.erase(std::remove(str.begin(), str.end(), ';'), str.end());
        return str;
    }

public:
    void parseDeclaration(const std::string& line) {
        std::stringstream ss(line);
        std::string type, token;
        ss >> type;
        while (ss >> token) {
            token = clean(token);
            if (token.empty()) continue;
            if (type == "input") netlist.inputs.push_back(token);
            if (type == "output") netlist.outputs.push_back(token);
        }
    }

    void parseAssignment(const std::string& line) {
        std::stringstream ss(line);
        std::string assign_kw, lhs, eq, rhs1, op, rhs2;
        
        ss >> assign_kw >> lhs >> eq >> rhs1;
        lhs = clean(lhs);
        rhs1 = clean(rhs1);

        YosysGate gate;
        gate.output_net = lhs;

        // Check if there is an operator following the first token
        if (ss >> op >> rhs2) {
            op = clean(op);
            rhs2 = clean(rhs2);
            if (op == "&") gate.type = "AND";
            else if (op == "|") gate.type = "OR";
            
            gate.input_nets.push_back(rhs1);
            gate.input_nets.push_back(rhs2);
        } else {
            // Check for explicit NOT inversion bit
            if (rhs1.find('~') != std::string::npos) {
                gate.type = "NOT";
                // Strip the '~' symbol to grab net name
                std::string clean_net = rhs1;
                clean_net.erase(std::remove(clean_net.begin(), clean_net.end(), '~'), clean_net.end());
                gate.input_nets.push_back(clean_net);
            }
        }

        // Track internal intermediate variables as wires
        if (std::find(netlist.outputs.begin(), netlist.outputs.end(), lhs) == netlist.outputs.end()) {
            if (std::find(netlist.wires.begin(), netlist.wires.end(), lhs) == netlist.wires.end()) {
                netlist.wires.push_back(lhs);
            }
        }
        netlist.gates.push_back(gate);
    }

    // Generates completely legal Yosys-internal AST Structural Verilog
    void exportToYosys(const std::string& module_name) {
        std::cout << "// Generated by Toy C++ Synthesis Compiler Engine\n";
        std::cout << "module " << module_name << "(\n";
        
        // Output ports list
        for (size_t i = 0; i < netlist.inputs.size(); ++i) {
            std::cout << "  input " << netlist.inputs[i] << ",\n";
        }
        for (size_t i = 0; i < netlist.outputs.size(); ++i) {
            std::cout << "  output " << netlist.outputs[i];
            if (i < netlist.outputs.size() - 1) std::cout << ",\n";
        }
        std::cout << "\n);\n\n";

        // Declare internal wires
        if (!netlist.wires.empty()) {
            std::cout << "  wire ";
            for (size_t i = 0; i < netlist.wires.size(); ++i) {
                std::cout << netlist.wires[i];
                if (i < netlist.wires.size() - 1) std::cout << ", ";
            }
            std::cout << ";\n\n";
        }

        // Instantiate compliant Yosys internal gate primitives
        for (size_t i = 0; i < netlist.gates.size(); ++i) {
            const auto& gate = netlist.gates[i];
            if (gate.type == "AND") {
                std::cout << "  \\$_AND_$ _" << i << "_ (\n"
                          << "    .A(" << gate.input_nets[0] << "),\n"
                          << "    .B(" << gate.input_nets[1] << "),\n"
                          << "    .Y(" << gate.output_net << ")\n"
                          << "  );\n";
            } else if (gate.type == "OR") {
                std::cout << "  \\$_OR_$ _" << i << "_ (\n"
                          << "    .A(" << gate.input_nets[0] << "),\n"
                          << "    .B(" << gate.input_nets[1] << "),\n"
                          << "    .Y(" << gate.output_net << ")\n"
                          << "  );\n";
            } else if (gate.type == "NOT") {
                std::cout << "  \\$_NOT_$ _" << i << "_ (\n"
                          << "    .A(" << gate.input_nets[0] << "),\n"
                          << "    .Y(" << gate.output_net << ")\n"
                          << "  );\n";
            }
            std::cout << "\n";
        }
        std::cout << "endmodule\n";
    }
};

int main() {
    YosysCompatibleSynthesizer synth;

    std::vector<std::string> source = {
        "input A B C ;",
        "output Y Z ;",
        "assign w1 = A & B ;",
        "assign Y = w1 | C ;",
        "assign Z = ~C ;"
    };

    for (const auto& line : source) {
        if (line.find("input") == 0 || line.find("output") == 0) synth.parseDeclaration(line);
        else if (line.find("assign") == 0) synth.parseAssignment(line);
    }

    synth.exportToYosys("synthesized_top");
    return 0;
}

